insta_clone/authentication/urls.py
from django.urls import path
from authentication.views import (
    SignUpView ,
    SignInView
    )

urlpatterns = [
    path('', SignInView.as_view(), name = 'signin_view'),
    path('signup/', SignUpView.as_view(), name = 'signup_view'),

]

insta_clone/insta_clone/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls'))
]

insta_clone/authentication/models.py
from django.db import models

# Create your models here.

insta_clone/common/models.py
from django.db import models

# Create your models here.

insta_clone/core/models.py
from django.db import models

# Create your models here.

insta_clone/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from user.managers import CustomUserManager
# from django.contrib.auth.base_user import BaseUserManager

# Create your models here.
class User(AbstractUser):
    picture = models.ImageField(upload_to='profile_pictures', null=False, blank=False)
    full_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    first_name = None
    last_name = None

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name',]

    objects = CustomUserManager()

    # AUTH_USER_MODEL  ='user.User'

    def __str__(self):
        return self.email

insta_clone/authentication/forms.py
from django import forms
# from user.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class UserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('full_name','email','username','password1','password2')

insta_clone/authentication/views.py
from django import forms
from django.http import request
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import View
from authentication.forms import UserForm

# Create your views here.


class SignUpView(View):
    template_name = 'authentication/signup.html'
    form_class = UserForm

    def get(self,request, *args, **kwargs):
        return render(request,self.template_name)

    def post(self,request, *args,**kwargs):

        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('form Save')
        
        context = {'form':form}

        return render(request,self.template_name,context)

class SignInView(View):
    template_name = 'authentication/signin.html'

    def get(self,request,*args,**kwargs):
        return render(request,self.template_name)
    
    def post(self,request,*args,**kwargs):
        


        


        return render(request,self.template_name)
    





    

insta_clone/common/views.py
from django.shortcuts import render

# Create your views here.

insta_clone/core/views.py
from django.shortcuts import render

# Create your views here.

insta_clone/user/views.py
from django.shortcuts import render

# Create your views here.

insta_clone/authentication/templates/authentication/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block extra_head %}{% endblock %}

    <title>Insta Clone</title>
  </head>
  <body>

    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block extra_body %}{% endblock %}

  </body>
</html>

insta_clone/authentication/templates/authentication/signin.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/signin.css' %}">
{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-6 d-none d-md-block">
            <img src="{% static 'img/phone_img.png' %}" class="signin__phone float-right">
        </div>
        <div class="col-sm-6 my-auto">
            <div class="">
                <div class="text-center card px-5 mr-md-auto signin__card">
                    <img src="{% static 'img/instalogo.png' %}" class="insta__logo mt-4 mb-3 mx-auto">
                    <div class="signin">
                        <div class="signin__form mb-3">
                            {% if messages %}
                                {% for message in messages %}
                                <div class="alert alert-danger" role='alert'>
                                    {{ message }}
                                </div>
                                {% endfor %}
                            {% endif %}
                            <form method="POST">
                                {% csrf_token %}
                                <div class="my-1 form__input">
                                    <input id="id_email_username" type="text" name="email_username" placeholder="Email or Username">
                                </div>
                                <div class="my-1 form__input">
                                    <input id="id_password" type="password" name="password" placeholder="Password">
                                </div>
                                <div class="my-4 mx-auto text-center">
                                    <button class="btn btn-sm auth__btn">Sign in</button>
                                </div>
                            </form>
                        </div>
                        <div class="text-center my-4">
                            <p class="or__text">OR</p>
                        </div>
                        <div class="my-1 mx-auto text-center">
                            <a class="login__fb__text text-decoration-none" href="">Log in with Facebook</a>
                        </div>
                        <div class="mb-4">
                            <a class="forogt__password text-decoration-none" href="{% url 'password_reset' %}">Forgot password?</a>
                        </div>
                    </div>
                </div>
                <div class="text-center card mt-2 px-5 mr-md-auto signin__card">
                    <p class="have__an__account py-3">Don't have an account? <a href="{% url 'signup_view' %}" class="text-decoration-none">Sign up</a></p>
                </div>
                <div class="text-center mt-2 px-5 mr-auto get__app">
                    <p class="">Get the app.</p>
                    <div class="row">
                        <div class="col-6">
                            <img src="{% static 'img/appstore.png' %}" class="app__download__img">
                        </div>
                        <div class="col-6">
                            <img src="{% static 'img/playstore.png' %}" class="app__download__img">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

insta_clone/authentication/templates/authentication/signup.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/signup.css' %}">
{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto signup__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mt-4 mb-3 mx-auto">
                <div class="signup">
                    <p class="signup__card__text">Sign up to see photos and videos from your friends.</p>
                    <div class="my-4 mx-auto text-center">
                        <button class="btn btn-sm auth__btn">Log in with Facebook</button>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div>
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif%}
                    </div>
                    <div class="signup__form mb-3">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="my-1 form__input">
                                <input id="id_email" type="email" name="email" placeholder="Email" class="form-control {% if form.email.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.email.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_username" type="text" name="username" placeholder="Username" class="form-control {% if form.username.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.username.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_full_name" type="text" name="full_name" placeholder="Full Name" class="form-control {% if form.full_name.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.full_name.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_password1" type="password" name="password1" placeholder="Password" class="form-control {% if form.password1s.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.password1.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_password2" type="password" name="password2" placeholder="Retype Password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.password2.errors }}
                                </div>
                            </div>
                            <div class="my-4 mx-auto text-center">
                                <button class="btn btn-sm auth__btn" type="submit">Sign up</button>
                            </div>
                        </form>
                    </div>
                    <p class="terms__conditions mb-4">By signing up, you agree to our <strong>Terms</strong> , <strong>Data Policy</strong> and <strong>Cookies Policy</strong> .</p>
                </div>
            </div>
            <div class="text-center card mt-2 px-5 mx-auto signup__card">
                <p class="have__an__account py-3">Have an account? <a href="" class="text-decoration-none">Sign in</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}